/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAgreementRouteImport } from './routes/service-agreement'
import { Route as FormTestRouteImport } from './routes/form-test'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPropertyCleanupRouteImport } from './routes/services.property-cleanup'
import { Route as ServicesLawnMaintenanceRouteImport } from './routes/services.lawn-maintenance'
import { Route as ServicesLandscapeMaintenanceRouteImport } from './routes/services.landscape-maintenance'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAgreementRoute = ServiceAgreementRouteImport.update({
  id: '/service-agreement',
  path: '/service-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const FormTestRoute = FormTestRouteImport.update({
  id: '/form-test',
  path: '/form-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPropertyCleanupRoute = ServicesPropertyCleanupRouteImport.update({
  id: '/property-cleanup',
  path: '/property-cleanup',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLawnMaintenanceRoute = ServicesLawnMaintenanceRouteImport.update({
  id: '/lawn-maintenance',
  path: '/lawn-maintenance',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLandscapeMaintenanceRoute =
  ServicesLandscapeMaintenanceRouteImport.update({
    id: '/landscape-maintenance',
    path: '/landscape-maintenance',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/form-test': typeof FormTestRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/landscape-maintenance': typeof ServicesLandscapeMaintenanceRoute
  '/services/lawn-maintenance': typeof ServicesLawnMaintenanceRoute
  '/services/property-cleanup': typeof ServicesPropertyCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/form-test': typeof FormTestRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/landscape-maintenance': typeof ServicesLandscapeMaintenanceRoute
  '/services/lawn-maintenance': typeof ServicesLawnMaintenanceRoute
  '/services/property-cleanup': typeof ServicesPropertyCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/form-test': typeof FormTestRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/landscape-maintenance': typeof ServicesLandscapeMaintenanceRoute
  '/services/lawn-maintenance': typeof ServicesLawnMaintenanceRoute
  '/services/property-cleanup': typeof ServicesPropertyCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/form-test'
    | '/service-agreement'
    | '/services'
    | '/services/landscape-maintenance'
    | '/services/lawn-maintenance'
    | '/services/property-cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/form-test'
    | '/service-agreement'
    | '/services'
    | '/services/landscape-maintenance'
    | '/services/lawn-maintenance'
    | '/services/property-cleanup'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/form-test'
    | '/service-agreement'
    | '/services'
    | '/services/landscape-maintenance'
    | '/services/lawn-maintenance'
    | '/services/property-cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FormTestRoute: typeof FormTestRoute
  ServiceAgreementRoute: typeof ServiceAgreementRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-agreement': {
      id: '/service-agreement'
      path: '/service-agreement'
      fullPath: '/service-agreement'
      preLoaderRoute: typeof ServiceAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-test': {
      id: '/form-test'
      path: '/form-test'
      fullPath: '/form-test'
      preLoaderRoute: typeof FormTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/property-cleanup': {
      id: '/services/property-cleanup'
      path: '/property-cleanup'
      fullPath: '/services/property-cleanup'
      preLoaderRoute: typeof ServicesPropertyCleanupRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/lawn-maintenance': {
      id: '/services/lawn-maintenance'
      path: '/lawn-maintenance'
      fullPath: '/services/lawn-maintenance'
      preLoaderRoute: typeof ServicesLawnMaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/landscape-maintenance': {
      id: '/services/landscape-maintenance'
      path: '/landscape-maintenance'
      fullPath: '/services/landscape-maintenance'
      preLoaderRoute: typeof ServicesLandscapeMaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesLandscapeMaintenanceRoute: typeof ServicesLandscapeMaintenanceRoute
  ServicesLawnMaintenanceRoute: typeof ServicesLawnMaintenanceRoute
  ServicesPropertyCleanupRoute: typeof ServicesPropertyCleanupRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesLandscapeMaintenanceRoute: ServicesLandscapeMaintenanceRoute,
  ServicesLawnMaintenanceRoute: ServicesLawnMaintenanceRoute,
  ServicesPropertyCleanupRoute: ServicesPropertyCleanupRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FormTestRoute: FormTestRoute,
  ServiceAgreementRoute: ServiceAgreementRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
